#!/bin/bash -e

case "$1" in
  configure)

  # conffiles
  . /usr/share/yavdr/helpers/conffiles
  install_conffile yavdr-base /etc/acpi/powerbtn.sh
  install_conffile yavdr-base /etc/default/grub
  install_conffile yavdr-base /etc/logrotate.conf
  install_conffile yavdr-base /etc/update-manager/release-upgrades

  # prefill hdf
  yavdr-db-tool -k system.grub.options -a preset -v "vmalloc=256m nohz=off acpi_enforce_resources=lax"
  yavdr-db-tool -k system.shutdown -a preset -v "s3"
  yavdr-db-tool -k system.wakeup.method -a preset -v "acpi"
  yavdr-db-tool -k system.wakeup.disable_usb -a preset -v "1"
  yavdr-db-tool -k system.sleep.module -a preset -v "uswsusp"
  yavdr-db-tool -k system.sleep.options -a preset -v "-f"

  # temlate files
  /usr/bin/yavdr-template-base

  # update grub
  /usr/sbin/update-grub

  # bash hack
  ln -sf /bin/bash /bin/sh

  ;;

esac

exit 0
