#!/bin/sh

if [ remove = "$1" ]; then

   dpkg-divert --package yavdr-base --remove --rename \
      --divert /var/lib/vdr/plugins/xine/noSignal4x3.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal4x3.mpg
   dpkg-divert --package yavdr-base --remove --rename \
      --divert /var/lib/vdr/plugins/xine/noSignal16x9.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal16x9.mpg
   dpkg-divert --package yavdr-base --remove --rename \
      --divert /usr/share/libxine1-xvdr/nosignal.mpg.dontremove /usr/share/libxine1-xvdr/nosignal.mpg

fi

#DEBHELPER#
