#!/bin/sh -e

if [ install = "$1" -o upgrade = "$1" ]; then

  # conffiles
  . /usr/share/yavdr/helpers/conffiles
  install_conffile yavdr-base /etc/acpi/powerbtn.sh
  install_conffile yavdr-base /etc/update-manager/release-upgrades

  # diverts
  dpkg-divert --package yavdr-base --add --rename --divert /var/lib/vdr/plugins/xine/noSignal4x3.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal4x3.mpg
  dpkg-divert --package yavdr-base --add --rename --divert /var/lib/vdr/plugins/xine/noSignal16x9.mpg.dontremove /var/lib/vdr/plugins/xine/noSignal16x9.mpg
  dpkg-divert --package yavdr-base --add --rename --divert /usr/share/libxine1-xvdr/nosignal.mpg.dontremove /usr/share/libxine1-xvdr/nosignal.mpg

fi
