#!/bin/bash

# log.level in WF:
# 0  off
# 1  error
# 2  warn
# 3  info
debug=`dbget system.log.level`
if [ -z "$debug" ]; then
  debug=0
fi

function loginfo()
{
    if [ $debug -gt 2 ]; then
        logger -p user.info "$1"
    fi
}

loginfo "starting mount-loader"

# load default values and overrides from /etc/default/vdr 
. /usr/lib/vdr/config-loader

loginfo "VIDEO_DIR=$VIDEO_DIR"

function checkmount()
{
    retry=3
    while [ $retry -gt 0 ]; do
        loginfo "testing for $1 ($retry)"
        touch $1/.update
        if [ $? -eq 0 ]; then
            loginfo "found $1"
            touch $VIDEO_DIR/.update
	    break
        else
            loginfo "sleeping"
	    sleep 3
            retry=$(expr $retry - 1)
        fi
    done
}

loginfo "executing mount-loader"

if [ -e /etc/auto.net.yavdr ]; then
    loginfo "searching for video directories"
    for d in `cat /etc/auto.net.yavdr | awk '!/^#/ && /fstype/ {print $1}'`; do
        checkmount $VIDEO_DIR/net/$d
    done
fi

