#!/bin/bash
# 
# Example:
# R60copy_epgimage <command> <path to .rec>
#
# R60copy_epgimage after /video0/hitec/Doku/%Die_stille_Revolution_der_Mechatronik/2004-04-23.15\:25.50.99.rec
# $1 <command>  after
# $2 <path to .rec> /video0/hitec/Doku/%Die_stille_Revolution_der_Mechatronik/2004-04-23.15\:25.50.99.rec
#
case $1 in 
	after)
		echo "Copy EPG-Image to $2"
		;;
	*)
		echo "Script needs two parameters. See example inside the script."
		exit 0
		;;
esac

# eventid for recording
ELINE=`grep "^E " $2/info*`
ELINE=${ELINE//E }
EVENTID=${ELINE// *}

EPGIMAGES=/var/cache/vdr/epgimages/

if [ ! -f $2/Cover-Enigma.jpg ]; then
   if [ -f $EPGIMAGES/$EVENTID.jpg ]; then # typo $EPGIMGAGES
      cp $EPGIMAGES/$EVENTID.jpg $2 # typo $EPGIMGAGES
      cd $2 # Wegen R50correct_videodirs   	
      ln -s $EVENTID.jpg Cover-Enigma.jpg
   fi
fi

