#!/bin/bash
# 
# Example:
# R60copy_epgimage <command> <path to .rec>
#
# R60copy_epgimage after /video0/hitec/Doku/%Die_stille_Revolution_der_Mechatronik/2004-04-23.15\:25.50.99.rec
# $1 <command>  after
# $2 <path to .rec> /video0/hitec/Doku/%Die_stille_Revolution_der_Mechatronik/2004-04-23.15\:25.50.99.rec
#

RECPATH=$2
CUTPATH=$3

# epg definitions
EPGIMAGESPATH="/var/cache/vdr/epgimages"
EPGIMAGESFORMAT="jpg"
COVER="Cover-Enigma"


# eventid for recording
geteventid() {
ELINE=`grep "^E " $RECPATH/info*`
ELINE=${ELINE//E }
EVENTID=${ELINE// *}
}

copyepgimages() {
while [ ! -f $RECPATH/info ]; do sleep 2; done
#if [ ! -f $RECPATH/$COVER.$EPGIMAGESFORMAT ]; then
	geteventid
	if [ -f $1/"$EVENTID"_0.$EPGIMAGESFORMAT ]; then
		SEARCH=`find $1 -name ""$EVENTID"_*.$EPGIMAGESFORMAT" | sort`;
		for i in $SEARCH ; do
			logger -t epgimage "Copy EPG Image for event ID $EVENTID: $i to $RECPATH"
			cp $i $RECPATH;
		done
		#cd $RECPATH
		#ln -s "$EVENTID"_0.$EPGIMAGESFORMAT $COVER.$EPGIMAGESFORMAT
	fi
#fi
}

case $1 in
	before)
		# do here whatever you would like to do right BEFORE
		# the recording $2 STARTS
		copyepgimages $EPGIMAGESPATH
		;;
	after)
		# do here whatever you would like to do right AFTER
		# the recording $2 ENDED
		#copyepgimages $EPGIMAGESPATH
		;;
	edited)
                # do here whatever you would like to do right AFTER
                # the recording $2 has been EDITED
                copyepgimages $CUTPATH 
		;;
        *)
                echo "Script needs two parameters. See example inside the script."
                exit 0
                ;;
esac
